name: t-iot-902

services:
  t-iot-902-api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: t-iot-902-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run dev"
